CUDA_VISIBLE_DEVICES=0,1 python main.py \
--gpu=2 \
--j=4 \
--init_type='xavier' \
--init_lr=1e-2 \
--weight_decay=5e-4 \
--momentum=0.9 \
--dataroot='/home/song/workspace/deeplab/dataset/VOCdevkit/VOC2012' \
--weights='/home/song/workspace/deeplab/weights/' \
--train_batchsize_per_gpu=12 \
--test_batchsize=12 \
--log_test_dir='/home/song/workspace/deeplab/tmp/log_test' \
--max_epoches=500 \
--test_epoches=10 \
--save_weights_epoches=10 \
--decay_every_epoches=10 \
--check_dataloader=True \
#--resume='/home/song/workspace/deeplab/weights/model-0140.pth.tar'